package com.padedatingapp.model.call

import android.os.Parcelable
import kotlinx.android.parcel.Parcelize
import kotlinx.android.parcel.RawValue
import java.io.Serializable


data class User2(
    val __v: Int,
    val _id: String,
    val accessToken: String,
    val address: String,
    val age: Int,
    val appleId: String,
    val blockedUsers: @RawValue List<Any>,
    val city: String,
    val country: String,
    val countryCode: String,
    val createdAt: String,
    val dateofbirth: String,
    val datingPreference: String,
    val description: String,
    val deviceToken: String,
    val deviceType: String,
    val docImage: @RawValue List<Any>,
    val doyoudrink: String,
    val doyousmoke: String,
    val educationLevel: String,
    val email: String,
    val ethnicity: String,
    val facebookId: String,
    val firstName: String,
    val gender: String,
    val geoPoint: GeoPointX,
    val googleId: String,
    val height: String,
    val heightInCms: Double,
    val image: String,
    val instagramId: String,
    val interestedIn: String,
    val isActive: Boolean,
    val isApproved: Boolean,
    val isBlocked: Boolean,
    val isDeleted: Boolean,
    val isEmailVerified: Boolean,
    val isNewUser: Boolean,
    val isNotification: Boolean,
    val isOnline: Boolean,
    val isPhoneVerified: Boolean,
    val lastName: String,
    val latitude: String,
    val longitude: String,
    val oneTimeCode: String,
    val password: String,
    val pendingAmount: String,
    val phoneNo: String,
    val profileStatus: Int,
    val religiousBelief: String,
    val state: String,
    val updatedAt: String,
    val username: String,
    val walletAmount: String,
    val work: String
): Serializable