package com.padedatingapp.model

class UserModel (
    val __v: Int,
    val _id: String,
    val accessToken: String,
    val address: String,
    val appleId: String,
    val city: String,
    val country: String,
    val countryCode: String,
    val createdAt: String,
    val dateofbirth: String,
    val datingPreference: String,
    val description: String,
    val deviceToken: String,
    val deviceType: String,
    val age: Int,
    val docImage: ArrayList<ImageModel>,
    val docNumber: String,
    val doyoudrink: String,
    val doyousmoke: String,
    val educationLevel: String,
    val email: String,
    val ethnicity: String,
    val facebookId: String,
    val firstName: String,
    val gender: String,
    val googleId: String,
    val height: String,
    val image: String,
    val isActive: Boolean,
    val isApproved: Boolean,
    val isBlocked: Boolean,
    val isDeleted: Boolean,
    val isEmailVerified: Boolean,
    val isNewUser: Boolean,
    val isNotification: Boolean,
    val isPhoneVerified: Boolean,
    val lastName: String,
    val latitude: String,
    val likes: List<Any>,
    val longitude: String,
    val oneTimeCode: String,
    val password: String,
    val pendingAmount: String,
    val phoneNo: String,
    val religiousBelief: String,
    val state: String,
    val updatedAt: String,
    val username: String,
    val walletAmount: String,
    val work: String,
    var profileStatus:Int,
    val interestedIn: String,
    val totalPoints: String


)

